### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1058]
Currently, everything that powers worldcubeassociation.org is on a single AWS EC2 m3.medium server. (I plan to switch this to a t2.medium soon, which seems to be better optimized for webservers)

Some potential future plans for improvement:

- [ ] Set up unicorn-worker-killer #1059.
- [x] Dedicated MySQL instance - Right now, MySQL runs on the same server as our rails application. If we split this out to its own dedicated machine (or use a managed db service like [Amazon RDS](https://aws.amazon.com/rds/)), that would open up a number of possible changes:
  - [ ] Multiple application servers
  - [ ] Run workers on a dedicated machine (this would allow us to run our "validate the entire db" script without fear of killing the production server #165)
  - [ ] Run database backups against a read replica of the database
  - [ ] Experiment with cool tools like redash (see #219) (ok, this won't help us scale, but is something we can't do until mysql is its own dedicated machine)
  - A better fix for #1066.
- [x] ~~ElasticSearch - We have a number of expensive LIKE queries that will only get more expensive over time. @pingskills worked to optimize some of these in #1051, but someday it will probably make sense to switch to something optimized for full text searches.~~ EDIT: See @larspetrus's post [below](https://github.com/thewca/worldcubeassociation.org/issues/1058#issuecomment-269845457).

**Comment by larspetrus** [comment]
I think the search problem can be fixed in an afternoon, by adding a MSQL FULLTEXT index and moving from `%term%` to `term%`¹ type queries. Once that is handled, we need to reevaluate what performance problem remains, if any.

Adding more (or faster) servers can help with many things, but it also costs a lot more.

¹ conceptually. The actual syntax is different.

**Comment by coder13** [comment]
We're currently running production on a t2.medium. This is causing problems with mysql mysql taking up 17% of the ram.

Jeremy and I talked about pulling out mysql and setting up a dedicated mysql server to reduce the load. This would be on a t2.small at $0.034/hour or ~$24.5/month.
We would then be running both a t2.small and t2.medium for about $0.087/hour or $62/month
If things are looking great, we would then shrink production down to t2.small to bring the total to $41/month.

**Comment by larspetrus** [comment]
I'm not convinced we know what's going on with this MySQL problem, but one good way to learn more is to test different configurations like splitting out to separate servers, and see what happens. Another approach is to run on something larger.

The thing that worries me with a separate DB is the added lag. That would also be a good thing to observe during a test like this.

**Comment by jfly** [comment]
> I'm not convinced we know what's going on with this MySQL problem

I'd go even further and say "we don't know that this is a MySQL problem". All I think we know for sure is that we get low on memory sometimes, and processes (understandably) start to crash. A strange possible red herring in the last crash was that MySQL looked to be starting to use a lot of CPU before crashing.

**Comment by jfly** [comment]
Pulling mysql out to RDS seems to have helped a lot here. I still think that some day we should consider spinning up a separate server dedicated to processing background jobs, but for now,.
