### ISSUE TITLE
Port PHP media stuff to Rails

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#296]
AFAIK, there are 4 pages to this:
- https://www.worldcubeassociation.org/results/media.php
- https://www.worldcubeassociation.org/results/media_insertion.php
- https://www.worldcubeassociation.org/results/admin/validate_media_ACTION.php?new42=634406671
- https://www.worldcubeassociation.org/results/admin/validate_media.php

We should also take this opportunity to remove the captcha on the media submission page, and instead require an account to submit. This would also allow us to change the `submitterName` field to a `user_id` field. Unfortunately, we won't have `user_id`s for all our existing media.

## TODO

Part of this issue was handled in #2071, but some work remains:

- [x] Delete old PHP approval page code 
- [x] Add a link (where?) for the WCT to actually get to this page
- [x] Port the media submission page to RoR as well

**Comment by SAuroux** [comment]
Today we had a media submission which was just the link to a random online casino/betting page. That's the first time I personally saw something like this, but if we get more such spam submissions in the near future proceeding with this issue could become more important.
