### ISSUE TITLE
[WCAT] Improvement of the competition form

### ISSUE THREAD

**Issue by DanielEgdal** [thewca/worldcubeassociation.org#3759]
WCAT would like to have the following updates to the competition form page to avoid issues from Delegates and organisers. 

- [ ] Make it impossible to confirm a competition before a schedule on the WCA Website is filled out.
- [ ] Always have all event information be listed before the competition can be confirmed. (This is to ensure the amount of rounds per event appears on the events page as well as the advancement conditions.) 
- [ ] Give warnings when the cutoff is set to be equal to or higher than the time limit.
- [ ] Make the “Reason for the name” box be mandatory to fill out before submitting a competition.
- [ ] Make it impossible to submit a competition which is less than 28 days from the scheduled start. (This is per the new regulations of 2019.)
- [ ] Remove the markdown text in the schedule tab which refers to the venue name. https://github.com/thewca/worldcubeassociation.org/issues/3634
- [ ] Create a standard form which allows WCAT to press a button on the website which sends out an automated message to all competitors to inform them of a newly added event. (I believe this message would be similar to when results of a competition is posted or the ones organisers receive once we announce their competition. When competitors are to respond to this mail, it should make the organiser(s) and Delegate(s) the default receiver, so they can easier update their registration to contain this event.)
- [ ] Only show the nickname field if the name is longer than 32 characters. (WCAT is already ensuring that all names at 32 or less characters have the same name and nickname.)
- [ ] Make it possible to view the events of nearby competitions in the nearby competitions field by a click. (I believe this is similar to the "edit/registrations?show_events=true" page of competitions. This is to easier compare the events of the competitions which have a conflict due to the proximity policy.)

Best, 
Daniel & WCAT

**Comment by AlbertoPdRF** [comment]
I was going to edit the first comment to include more related issues, but I will for now reference them separately as the list is bigger than what I was expecting :stuck_out_tongue: 

- [ ] Rename registrations fields (#3693)
- [ ] Updates to Registration Requirements (#3526, #3267)
- [ ] Showing if a championship type is already in use for the year (#3225)
  - Actually, shouldn't we just prevent confirming a competition that selected a championship type already in use for the year?
- [ ] Improvements to the base entry fee (#3105)
- [ ] Log of edits to competitions. (#3042)
- [ ] Update to Create Competition Form (#2472)
  - This issue needs updating, see https://github.com/thewca/wca-regulations/pull/673 and https://github.com/thewca/wca-documents/pull/40 for reference.
- [ ] Add UI for setting entry fees for each event (#2444)
- [ ] Time Zone Functionality for Registration Open/Close (#1799)
- [ ] Unified edit competition page (?) (#1331)
  - It should be decided if we want this, and if not, close the issue.
- [ ] Add the ISO Code along with the description for the list of currencies (#995)
- [ ] Datetimepicker bug? (#751)
- [ ] Decide how to handle markdown fields on competition edit page (#663)
  - Not sure if this issue is still relevant, I'm listing it just in case.
- [ ] Consistency of competition address and coordinates (#217)

I also left comments on some related issues that I believe should be closed instead of including them here.

**Comment by jamesquinn1** [comment]
> * [ ]  Showing if a championship type is already in use for the year (#3225)
>   
>   * Actually, shouldn't we just prevent confirming a competition that selected a championship type already in use for the year?

This has been allowed in the past (or has happened at least). Would this no longer be allowed?
Personally I am for not allowing multiple National (or Continental/World) Championships in one year, but idk if consistency would be an issue.

**Comment by viroulep** [comment]
>This has been allowed in the past (or has happened at least).

I was curious so I looked it up, it happened in Brazil in 2014 ([here](BrasileiroInverno2014), and [here](BrasileiroVerao2014)), I'll comment in the relevant issue.

**Comment by jamesquinn1** [comment]
> * Only show the nickname field if the name is longer than 32 characters. (WCAT is already ensuring that all names at 32 or less characters have the same name and nickname.)

Why can't competitions with names shorter than that have nicknames?

**Comment by Jambrose777** [comment]
Addition:
- [] Have the ID field only be editable on the admin page. Otherwise it is always the same as the nickname.

**Comment by Epride** [comment]
> - [ ] Make the competitor limit required.

Wouldn't this become an issue with multi-location FMC competitions which generally don't specify a limit?

**Comment by DanielEgdal** [comment]
> > * [ ]  Make the competitor limit required.
> 
> Wouldn't this become an issue with multi-location FMC competitions which generally don't specify a limit?

Yes it would be an issue with those competitions, but I assume a simple extenstion to #3755 would fix this issue for the competitor limit as well.

**Comment by jfly** [comment]
There's a ton of stuff in here, but @Mjic99 will start looking into it after https://github.com/thewca/worldcubeassociation.org/issues/4069.

**Comment by AlbertoPdRF** [comment]
Yet another addition:

- [ ] Read-only competition mode (#4219)

At this point, I think it would make the most sense to convert this issue into a project!

**Comment by Jambrose777** [comment]
- [ ] Add similar regulation check box for asking for restrictions to combination of events.

**Comment by AlbertoPdRF** [comment]
I've created a project for this issue (as it has many standalone requests) as well as for all the issues listed within it, as it has grown so big that I don't see any other way to manage it :stuck_out_tongue: You can see it on: https://github.com/thewca/worldcubeassociation.org/projects/8

**Comment by viroulep** [comment]
FWIW I think the overall "competition edit" page would be a good candidate to be ported to js/react given the amount of interaction there is now.

**Comment by AlbertoPdRF** [comment]
> FWIW I think the overall "competition edit" page would be a good candidate to be ported to js/react given the amount of interaction there is now.

Should we move this to its own issue? It seems like a big task to me.

**Comment by viroulep** [comment]
oh for sure it's big!
This is probably for after we've done some software "cleaning" steps for the website redesign.

**Comment by jfly** [comment]
For the record, we currently leverage a *lot* of magical integrations between activerecord validations and simple_form. Moving the competition edit page to js/react would mean we'd lose all of that.

I'm not sure I'm convinced that there's enough fancy interaction on the competition edit page that it's worth porting to react. The one thing I can think of is the nearby competitions check, which is pretty janky, and would definitely be clearer in pure js. Maybe it would be possible to divide the edit page up into multiple smaller forms? That might help with maintainability and also make it easier to port parts to react if we decide it's worth it.
