### ISSUE TITLE
Handle Delegates on probation similarly to banned competitors

### ISSUE THREAD

**Issue by AlbertoPdRF** [thewca/worldcubeassociation.org#3885]
**Is your feature request related to a problem? Please describe.**
Handling Delegates on probation now is done through a spreadsheet, which is a sub-par solution.

**Describe the solution you'd like**
A solution similar to how banned competitors are handled seems ideal.

**Comment by cubewhiz** [comment]
In particular, it would be useful for WCAT to know if a Delegate is on probation when the Delegate confirms a competition. Perhaps a quick fix is to add some sort of checkbox on the Delegate's user page which, if checked, would add a bold red line in auto generated email when that Delegate confirms a competition that the WCAT should check the probationary terms before proceeding.

**Comment by Jambrose777** [comment]
I'd like to work on this! I'll ping slack when I have any questions.

**Comment by Jambrose777** [comment]
- [ ] implement Delegates on probation as a hidden team.
- [ ] Let Seniors modify the probation team.
- [ ] When a competition submitted by a Delegate on probation, inform WCAT of the probationary status.
- [ ] When adding a Delegate to the probation team, send an email to WQAC, Senior, Delegate, and Board
- [ ] Add table for extra fields: End Terms, Restrictions, Reason

**Comment by AlbertoPdRF** [comment]
I've never assigned this issue to @Jambrose777, so I'm doing it now!

**Comment by danieljames-dj** [comment]
I'm closing this issue as this has been mostly finished now.

I'm highlighting few points which are not yet checked by @Jambrose777 along with clarification why it cannot be implemented now:

- When adding a Delegate to the probation team, sends an email to WQAC, Senior, Delegate, and Board
Sending email to Senior Delegate & Board, and not to WQAC. Hope this is fine and WST haven't received a requirement that WQAC should also be mailed. If this requirement is said by WQAC or Board, we will definitely consider it. The change will just adding WQAC to the "to list".

- Add table for extra fields: End Terms, Restrictions, Reason. (progress column?)
Not adding because those are currently maintained in spreadsheet and having it in table will give access to WST & WRT as well because they have access to the full database. If Board is fine with sharing this with WRT & WST as well, then this can be done.

- Make it to where only Delegates can be on the probation team. (May not be necessary - also wouldn't apply for past members of the team)
The website allows to add only Delegates to probation. We don't have backend validation though.

- Make probations automatic for late reports and getting off probation automatic. Requires a lot of research and probably isnt feasible yet.
This can also be done if needed, but not sure if this is a requirement now. If it comes as a requirement, we can consider.

(cc-ing @thewca/board as well to keep you informed about it)

Please feel free to reopen if anything has to be implemented.
