### ISSUE TITLE
Dues Implementation

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#4199]
The Dues Policy has been in place for over a year now and has got to a place where it is reasonably well automated. However it is still completely separate from the WCA website. In the short term we would like some form of lite integration with the website, so that delegates can see Dues within the WCA website, and be taken to external pages to pay, etc. In the long term our goal is to have invoices automatically generated once results are submitted, payment options embedded within the website, with all the necessary admin pages the WFC might need.

[Xero API Overview](https://developer.xero.com/documentation/api/api-overview)

### Information and Lite Integration/Automation
**Competition Page**
- [ ] New tab on the competition page under delegate report titled "Dues" - Visible to listed delegates, WFC, & admin.
- [ ] Checkbox visible for WFC - Unchecked shows "Unpaid" and checked shows "Paid" to delegates. 
- [ ] Remove above and add API check to see whether invoice is paid per Xero.
- [ ] API to grab a link to the invoice based off the Reference (CompetitionID).
- [ ] Embed PDF of invoice within the page.
- [ ] Add buttons for all payment services.

**My Competitions**
- [ ] Add icon similar to delegate reports that takes delegate to Dues page for the competition.
- [ ] Shows warning icon that Dues need to be paid.

### Finance Pages
- [x] ~Create Finance pages, link accessible from profile (similar to Panel, manage users etc.)~ #4708
- [x] ~Country Bands page - Allow delegates and staff to see a page with a list of countries and their current banding. Should be listed alphabetically by default and contain a continent column as well as band. Allow the user to filter data by band or continent.~ #4713
- [x] ~Country Bands admin page - Visible to WFC to update country bands at a certain date. Similar to how WCA staff dates are updated.~ #4713
- [ ] Invoices page - Shows a list of all outstanding invoices sorted by invoice number. WFC can see all outstanding invoices, delegates can see outstanding invoices for their competitions. Allow delegates to select a number of invoices and make a single payment for multiple invoices.

### Automation
- [ ] Manage Contacts page - Visible to WFC that allows setting up of contacts for invoice purposes. For example all competitions that happen in the UK get invoiced to the UK Cube Association. Would allow a variety of different methods of invoicing depending on needs of the delegates.
- [ ] Upon results being uploaded, automatically trigger an event that issues the invoice based on the country band and number of competitors. Issued on Xero directly to contact if available, first listed delegate otherwise, however still emails all listed delegates and organisers.
- [ ] Provide notification for WFC members when an invoice becomes more than 30 days overdue to investigate for probation.

This is a work in progress and will be updated as and when. If anyone is interested in taking up this job please let me know and we can arrange meetings for design etc.

**Comment by AlbertoPdRF** [comment]
Given how huge this issue is, maybe we should split it into several smaller ones and have a dedicated project for them?

**Comment by Mollerz** [comment]
Making it a project and splitting it down might be the way forward as there is obviously a lot involved here. I do not have permissions to be able to create a project at the moment, I'm happy for someone else to build it if needed.

**Comment by AlbertoPdRF** [comment]
I've just created the project: https://github.com/thewca/worldcubeassociation.org/projects/7

**Comment by dunkOnIT** [comment]
@EdHollingdale 5 years on, I'd imagine WFC has found a way to survive - it would be helpful to know whether this issue is still generally accurate to WFC's needs, or if it's outdated enough that a generic "WFC software support"-type issue might be appropriate.

No need for in-depth explanations - a general yes keep it/no close it indication is fine - but if this triggers an essay on what would be helpful to WFC going into 2025 feel free to write it!

**Comment by EdHollingdale** [comment]
>  if it's outdated enough that a generic "WFC software support"-type issue might be appropriate.

I think a "WFC software support" type issue with an updated checklist taking us towards a new strategic vision for WFC software integration would be a better solution, and that this issue can be closed. 

I'll add to the WFC's tasks to have a conversation about what that target vision and the interim steps should be (and involve WST when appropriate). But I already think with a lot of the stuff @danieljames-dj has done the last few years with website support for combined invoices, dues redirects, and additional calculations in the Dues export is taking us in a slightly different direction to what this issue outlined (and it is a direction which more achievable as a sequence of step by step changes, as Daniel has made).
