### ISSUE TITLE
Compile April Milestones

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6824]
- [x] Check in with team what they're currently working on 
- [x] Add items to April Milestone (including retro-actively)
- [ ] Create "Compile May Milestones" issue, with due date for end of the month
