### ISSUE TITLE
Compile May Milestone

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6825]
- [x] Check with team what they'd like to work on for May
- [x] Add items to May Milestone (including retro-actively)
- [ ] Create "Compile June Milestones" issue, with due date for end of the month
- [x] action for June: checkin with team members who said they might be available later in May)
