### ISSUE TITLE
React Transition Roadmap

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6826]
Lots of interest in helping with the switch to React from the team, but a roadmap on how to do that / sense of architecture of the site would go a long way to helping.

- [ ] Basic architecture documentation (this may already exist)
- [ ] General roadmap/set of tasks
- [ ] Few "good first issues" for the React transition, to help people get familiar with the process

**Comment by dunkOnIT** [comment]
Not sure if creating stuff like this pre-emptively is helpful to be honest

**Comment by dunkOnIT** [comment]
noting this isn't completed, but it will happen naturally as part of strategic planning
