### ISSUE TITLE
Compile June Milestones (by 29/05/2022)

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#6908]
- [ ] Roll over unclosed issues/PR's
- [ ] Close previous month's milestone
- [ ] Confirm action items with each team member via Slack (including confirming whether they are still working on rolled-over issues)
- [ ] Create next month milestones task
